name: "New Chapter"
description: "Adding a new Chapter/Topic into the Documentation!"
title: "Chapter - "
label: ["Chapter"]
body: 
- type: markdown
  attributes:
    value: Thank you for contributing to our project knowledge base ! <3
- type: input
  id: topic
  attributes:
    label: Topic
    description: What Topic do you want to describe?
    placeholder: Where are the stones at?
- type: textarea
  id : description
  attributes:
    label: Detailed Description
    description: Please describe what points this topics documentation should include!
    placeholder: ...
- type: input
  id: reason
  attributes:
    label: Reason
    description: Why do we need this documented piece of art?
    placeholder: Because ...
